Repository satlayer/satlayer-bvs, pull requests merged in 2025-06, with the labels that each got.

#707 chore: updated whitepaper
  docs/public/assets/whitepaper.pdf
Labels: a/docs

#713 chore: bump pnpm to v10
  docs/package.json
  package.json
  packages/cli/satlayer.js
  packages/config-prettier/index.cjs
  packages/config-prettier/package.json
  pnpm-lock.yaml
  prettier.config.js
Labels: s/chore, a/docs

#717 chore: remove lib remappings.mjs and setup upgradeable contracts
  contracts/contracts.iml
  contracts/package.json
  contracts/remappings.mjs
  contracts/remappings.txt
  contracts/src/SLAYVault.sol
  contracts/test/MockERC20.sol
  contracts/test/SLAYVault.t.sol
Labels: s/chore

#718 feat: set up proxy pattern for immutable contract addresses
  contracts/src/EmptyImpl.sol
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYRouter.sol
  contracts/test/SLAYRegistry.t.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/SLAYTestSuite.sol
  contracts/test/SLAYVault.t.sol
Labels: s/feat

#720 chore: cosmwasm-optimizer more customizability
  packages/cosmwasm-optimizer/bin.js
Labels: s/chore

#721 chore: add cosmwasm-schema-cli to generate schema for any rust contract
  packages/cosmwasm-schema-cli/README.md
  packages/cosmwasm-schema-cli/package.json
  packages/cosmwasm-schema-cli/schema-gen.mjs
  pnpm-lock.yaml
Labels: s/chore

#722 chore: setup evm beacon pattern for Vault
  contracts/src/EmptyImpl.sol
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYRouter.sol
  contracts/src/SLAYVault.sol
  contracts/src/SLAYVaultFactory.sol
  contracts/test/SLAYRegistry.t.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/SLAYVault.t.sol
  contracts/test/TestSuite.sol
Labels: s/chore

#727 chore: set default solc version
  contracts/LICENSE
  contracts/foundry.toml
  contracts/script/Deployment.s.sol
  contracts/src/EmptyImpl.sol
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYRouter.sol
  contracts/src/SLAYVault.sol
  contracts/src/SLAYVaultFactory.sol
  contracts/test/MockERC20.sol
  contracts/test/SLAYRegistry.t.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/SLAYVault.t.sol
  contracts/test/TestSuite.sol
Labels: s/chore

#732 feat: SLAYRouter whitelist and pausable implementation
  contracts/src/SLAYRouter.sol
  contracts/src/SLAYVault.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/SLAYVault.t.sol
  contracts/test/TestSuite.sol
Labels: s/feat

#738 chore(workflows): ignore md,mdx from prettier to make docs edit easier
  .prettierignore
Labels: s/chore

#740 feat: SLAYRegistry service operator relationship
  contracts/src/SLAYRegistry.sol
  contracts/test/SLAYRegistry.t.sol
Labels: s/feat

#741 feat: implement _checkOperator for VaultFactory
  contracts/src/SLAYVaultFactory.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/SLAYVault.t.sol
  contracts/test/SLAYVaultFactory.t.sol
  contracts/test/TestSuite.sol
Labels: s/feat

#744 feat: solidity contracts deployment scripts
  contracts/script/Deployment.s.sol
  contracts/src/InitialImpl.sol
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYRouter.sol
  contracts/test/SLAYRegistry.t.sol
  contracts/test/TestSuite.sol
Labels: s/feat

#745 chore: use OZ validateImplementation and validateUpgrade for scripts before deployment
  contracts/script/Deployment.s.sol
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYRouter.sol
  contracts/src/SLAYVault.sol
  contracts/src/SLAYVaultFactory.sol
  contracts/test/TestSuite.sol
Labels: s/chore

#743 feat: erc-7540 async vault redeem
  .idea/satlayer-bvs.iml
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYVault.sol
  contracts/src/interface/IERC7540.sol
  contracts/test/SLAYRegistry.t.sol
  contracts/test/SLAYVault.t.sol
  contracts/test/SLAYVaultFactory.t.sol
Labels: s/feat

#757 chore: add interface to Router and VaultFactory
  contracts/src/SLAYRouter.sol
  contracts/src/SLAYVaultFactory.sol
  contracts/src/interface/ISLAYRegistry.sol
  contracts/src/interface/ISLAYRouter.sol
  contracts/src/interface/ISLAYVaultFactory.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/SLAYVaultFactory.t.sol
Labels: s/chore

#755 feat: move pausability to `InitialImpl`
  contracts/script/Deployment.s.sol
  contracts/src/InitialImpl.sol
  contracts/src/SLAYRegistry.sol
  contracts/src/SLAYRouter.sol
  contracts/src/SLAYVault.sol
  contracts/test/InitialImpl.t.sol
  contracts/test/SLAYRegistry.t.sol
  contracts/test/SLAYRouter.t.sol
  contracts/test/TestSuite.sol
Labels: s/feat

#767 chore(docs): examples update for clarity
  docs/app/page.mdx
  docs/public/assets/intro-satlayer.png
  examples/insurance/README.md
  examples/squaring/README.mdx
Labels: s/chore, a/examples, a/docs
